AeroLineaProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.inicio.urls')),
    path('', include('aplicaciones.empleado.urls')),
    path('', include('aplicaciones.login.urls')),
    path('captcha/', include('captcha.urls')),
]

aplicaciones/inicio/urls.py
from django.urls import path
from . import views
app_name = 'inicio_app'
urlpatterns = [
    path('', views.inicio, name = 'inicio'),
    path('listarpersonas/',views.listar_personas)
]

aplicaciones/login/urls.py
from django.urls import path, include
from . import views
app_name = 'login_app'

urlpatterns = [
    path('login/nuevo-usuario/', views.nuevo_usuario, name = 'nuevo-usuario'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.cerrar_sesion, name = "logout"),
    path('locked/', views.locked, name = "locked")

]

aplicaciones/inicio/models.py
from django.db import models

# Create your models here.

aplicaciones/inicio/views.py
from django.shortcuts import render

# Create your views here.
def inicio(request):
    return render(request, 'inicio/index.html')

def listar_personas(request):
    lista_personas = {
        "titulo": 'Lista de personas',
        "personas": [{'nombre':'juan','edad':12}, {'nombre':'jose','edad':23}, {'nombre':'juan','edad':12}]
    }
    return render(request, "inicio/listar_personas.html",lista_personas)

templates/inicio/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pagina inicial</title>
</head>
<body>
  {% if request.user.is_authenticated %}
    <h1>Bienvenido {{ request.user.username }}</h1>
    <a href="{% url 'login_app:logout' %}">Cerrar sesion</a>
  {% else %}
    <h2>Accesos denegado, debe iniciar sesion o registrate</h2>
    <a href="{% url 'login_app:login' %}"> Login</a>
    <a href="{% url 'login_app:nuevo-usuario' %}">Registrarse</a>
  {% endif%}
</body>
</html>

templates/inicio/listar_personas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Document</title>
    <style>
        table,th,td{
            border:thin black solid;
        }
        table{
            border-collapse: collapse;
        }

    </style>
</head>
<body>
    <h1>{{titulo}}</h1>
    <table>
        <thead>
            <th>Nombre</th>
            <th>Edad</th>
        </thead>
        <tbody>
            {% for persona in personas %}
                <tr>
                    <td>{{ persona.nombre }}</td>
                    <td>{{ persona.edad }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>