AeroLineaProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.inicio.urls')),
    path('', include('aplicaciones.empleado.urls')),
    path('', include('aplicaciones.login.urls')),
    path('captcha/', include('captcha.urls')),
]

aplicaciones/empleado/urls.py
from django.urls import path
from . import views
app_name = 'empleados_app'
urlpatterns = [
    path('empleado/crear-empleado/', views.CrearEmpleado.as_view(), name = 'crear-empleado'),
    path('empleado/crear-empleado2/', views.CrearEmpleado2.as_view(), name = 'crear-empleado2'),
    path('empleado/listar-empleados/', views.ListarEmpleados.as_view(), name = 'listar-empleados'),
    path('empleado/modificar-empleados/<pk>/', views.ModificarEmpleado.as_view(), name = 'modificar-empleados'),
    path('empleado/eliminar-empleados/<pk>/', views.EliminarEmpleado.as_view(), name = 'eliminar-empleados')


]

aplicaciones/empleado/models.py
from django.db import models

# Create your models here.
class Cargo(models.Model):
    idcargo = models.BigAutoField(primary_key=True) #django coloca el id implicito si no se escribe
    cargo = models.CharField('Cargo', max_length=50)

    def __str__(self) :
        return self.cargo
    

class Empleado(models.Model):
    nombre = models.CharField('Nombre', max_length=50)
    correo = models.CharField('Correo', max_length=100)
    sueldo = models.DecimalField('Sueldo', max_digits=8, decimal_places=2)
    activo = models.BooleanField('Activo')
    cargo = models.ForeignKey(Cargo, on_delete=models.RESTRICT)

    def __str__(self):
        return self.nombre + ' | ' + self.correo + ' | '+ str(self.activo)

aplicaciones/empleado/forms.py
from django import forms
from django.forms import ModelForm

from .models import Empleado

class EmpleadoForm(ModelForm):
    correo = forms.EmailField(max_length=200)
    class Meta:
        model = Empleado
        fields = ['nombre', 'correo', 'sueldo', 'activo', 'cargo']
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'})
        }
    def clean_correo(self) :
        email = self.cleaned_data['correo']
        lista = Empleado.objects.filter(correo = email).exclude(id = self.instance.id)
        print(self.instance.id)
        if lista:
            self.add_error('correo', 'El correo ya existe')

        if not email.endswith(('gmail.com', 'yahoo.com')):
            self.add_error('correo', 'El dominio no es valido')
        return email

aplicaciones/empleado/views.py
from django.shortcuts import render
from .models import Cargo, Empleado
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import EmpleadoForm
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# Create your views here.
@method_decorator(login_required, name='dispatch')
class ModificarEmpleado(PermissionRequiredMixin, UpdateView):
    permission_required = ('empleado.change_empleado')
    template_name = "empleados/modificar-empleado.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy("empleados_app:listar-empleados")

class ListarEmpleados(LoginRequiredMixin,ListView):
    template_name = 'empleados/listar-empleados.html'
    model = Empleado
    context_object_name = 'lista_empleados'
    queryset = Empleado.objects.filter(activo=True)
    paginate_by = 5

    def get_queryset(self) :
        nombre = self.request.GET.get('buscar')
        lista_empleado = Empleado.objects.filter(activo=True)
        if nombre :
            lista_empleado = Empleado.objects.filter(nombre__icontains=nombre)

        return lista_empleado
    
# formulario creado por vista generica generado solo con un modelo
class CrearEmpleado2(CreateView):
    model = Empleado
    template_name = "empleados/crear-empleado.html"
    fields = ['nombre', 'correo', 'sueldo', 'activo','cargo']
    success_url = reverse_lazy("empleados_app:listar-empleados")

# formulario creado por vista generica generado solo con un form model
class CrearEmpleado(LoginRequiredMixin,CreateView):
    form_class = EmpleadoForm
    template_name = "empleados/crear-empleado.html"
    success_url = reverse_lazy("empleados_app:listar-empleados")



class EliminarEmpleado(DeleteView):
    template_name = 'empleados/eliminar-empleado.html'
    model = Empleado
    success_url = reverse_lazy('empleados_app:listar-empleados')

templates/empleados/crear-empleado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Nuevo empleado</h2>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="Guardar">
    </form>
</body>
</html>

templates/empleados/eliminar-empleado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar empleado</title>
</head>
<body>
    <h2>Eliminar empleado</h2>
    <form action="" method="post">
        {% csrf_token %}
        <p>Desea eliminar el empleado seleccionado?</p>
        <input type="submit" value="Si">
        <a href="{% url 'empleados_app:listar-empleados' %}">Regresar</a>
    </form>
</body>
</html>

templates/empleados/listar-empleados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de empleados</title>
    <style>
        
        body {
            font-family: sans-serif ;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        tr:hover {background-color: coral;}

        input[type=text] {
            width: 30%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 3px solid #ccc;
            -webkit-transition: 0.5s;
            transition: 0.5s;
            outline: none;
            }

            input[type=text]:focus {
            border: 3px solid #555;
            }   
    </style>
</head>
<body>
    <h2>Lista de empleados</h2>
    <a href="{% url 'empleados_app:crear-empleado'%}">Nuevo empleado</a>
    <br>
    <br>
    <form action="" method="get">
        <input type="text" name="buscar" placeholder="Search" id="buscar">
    </form>
    <table>
        <thead>
            <tr><th>ID</th><th>Nombre</th><th>Cargo</th><th>Operaciones</th></tr>
        </thead>
        <tbody>
            {% for empleado in lista_empleados %}
                <tr>
                    <td>{{empleado.id}}</td>
                    <td>{{ empleado.nombre }}</td>
                    <td>{{ empleado.cargo }}</td>
                    <td>
                        <a href="{% url 'empleados_app:modificar-empleados' empleado.id%}">Editar</a> 
                        <a href="{% url 'empleados_app:eliminar-empleados' empleado.id%}">Eliminar</a>
                    </td>
                </tr>    
            {% endfor %}
        </tbody>
    </table>
    <br>

    {% if is_paginated %}
    
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previus_page_number}}"> < </a>
            
        {% endif %}    
        {% for pagenumber in paginator.page_range %}
        
            {% if page_obj.number == pagenumber %}
                <span>{{pagenumber}}</span>
            {% else %}
                <a href="?page={{pagenumber}}">{{pagenumber}}</a>
                
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">></a>
        {% endif %}
    {% endif %}
</body>
</html>

templates/empleados/modificar-empleado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <a href="{% url 'empleados_app:listar-empleados' %}">Lista empleados</a>
    <h2>Actualizar empleado</h2>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <div>
                {{form.nombre.label_tag}}
                {{form.nombre}}
                {{ form.nombre.errors }}
            </div>
           
            <div>
                {{form.correo.label_tag}}
                {{form.correo}}
                {{ form.correo.errors }}
            </div>
            <div>
                {{form.sueldo.label_tag}}
                {{form.sueldo}}
                {{ form.sueldo.errors }}
            </div>
            <div>
                {{form.cargo.label_tag}}
                {{form.cargo}}
                {{ form.cargo.errors }}
            </div>
            <div>
                {{form.activo.label_tag}}
                {{form.activo}}
                {{ form.activo.errors }}
            </div>
        </table>
        <input type="submit" value="Actualizar">
    </form>
</body>
</html>